# Generated by Django 4.2.7 on 2023-12-21 10:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('singleapp', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='careerapplication',
            name='zip_code',
        ),
        migrations.AlterField(
            model_name='careerapplication',
            name='plf',
            field=models.TextField(max_length=100),
        ),
    ]
